### ISSUE TITLE
Experiment: FetchTree Boundary

### ISSUE THREAD

**Issue by AsaAyers** [unizin/fetch-tree#20]
When you wrap a component in `fetchTree`, it creates [a `loaderContext`](https://github.com/unizin/fetch-tree/blob/f523cea57cf40d8eefb2af96843105d8b0c9b697/src/loader_context.js) and attaches it to React's context.

I think it may be a good idea to split this into its own component that you might choose to place at the top of your app.

```
    <App>
        <Match component={FetchTreeWrappedA} />
        <Match component={FetchTreeWrappedB} />
    <App>
```

Today, those two components would have different `loaderContext`, so the cache is totally cleared when you move between routes.

Having a parent LoaderContext would allow the cache to be maintained through route changes:

```
    <App>
        <LoaderContext>
            <Match component={FetchTreeWrappedA} />
            <Match component={FetchTreeWrappedB} />
        </LoaderContext>
    <App>
```

**Comment by AsaAyers** [comment]
This is not a good plan.

The loaderContext prevents re-fetching the same `loader()` or `entity()` on every render. Before the name fetch-tree, the data to know whether or not something was loaded was in the store. The result was that once you loaded an entity, you could never fetch an updated copy because it was permanently marked as already available.

Adding `<LoaderContext` brings us back to that state, where once a `loader()` or `entity()` has been fetched, it will never be fetched again.

**Comment by dcgleim** [comment]
Awe, I like this plan.  I like that the component that provides the context is different than the component that consumes it.

Also, solving the re-fetching issue by changing locations (or doing whatever to change your top-level fetch-tree component) seems cumbersome.  I think there's always going to be pressure to allow keeping that cache, while invalidating specific parts of it.  I given it zero thought, but perhaps an action can be provided by fetch-tree to components to allow invalidating the current resource's cache with the given args.

**Comment by AsaAyers** [comment]
There are two caches involved here:

1. Has X been fetched? / Do I need to fetch X?
2. What is the data for X

The first one is stored in `loaderContext` the other is stored in Redux's store.

In the example above, lets say `FetchTreeWrapperA` and `FetchTreeWrapperB` both used `todo-4`. When you launch the app and land in A, it fetches the todo and renders it. When you navigate to B, it renders the stored todo immediately without a loading screen, but it also fetches a fresh copy in the background.

Adding this parent `<LoaderContext` as proposed would prevent B from fetching a fresh copy. You're permanently stuck with whatever representation of that object you got when you loaded the app.

**Comment by dcgleim** [comment]
Right.  And I still think this proposal is worth solving that for.  While an extra network request might not be a huge deal, it had to be part of the reason you opened this in the first place.  And true, we'd need to expand to somehow expose cache controls, but I nonetheless think a ContextProvider/ContextConsumer pair makes a lot of sense, and would open options for solving other problems like those around connected components.
