### ISSUE TITLE
Remove `lazy` and `preload` in favor of expanded `group`?

### ISSUE THREAD

**Issue by dcgleim** [unizin/fetch-tree#7]
@cbranch101 and I observed the following

- `group` defines a set of nodes at component definition-time. `lazy` allows defining new nodes later, and only a group would really be useful.  As such, would it be clearer if `group` could accept a function to later return a group object, taking over the job of `lazy`?

- These two examples seem similar enough to become the same.  Why does only one return an explicit new group?  Why does one use the `useProps` while the other `depends.value`? 

```js
lazy((ids) => group(ids.map(
    id => depends([depends.value(id)], todoLoader)
))))

preload((useProps, ids) => ids.map(
    id => useProps({ id }, todoResources)
))
```

Taken together, a `preload` could become like below?  To emulate the current `lazy`, you'd not include `virtual`. 

```js
const todoListResources = group({
    todos: virtual(depends(
        [depends.prop('ids')],
        group(
            (useProps, ids) => ids.map(
                id => depends([depends.value[id], todoResources)
            )
        )
    ))
})
```

/cc @AsaAyers

**Comment by AsaAyers** [comment]
These have been deprecated and can be removed when we want a 2.0. See #12

**Comment by cbranch101** [comment]
Should we close this?
